name: Build Windows Libraries

on:
  workflow_dispatch: # 只允许手动触发

jobs:
  build-windows-libs:
    runs-on: windows-latest
    
    steps:
    - name: Install MySQL libraries
      run: |
        cd vcpkg
        # 使用正确的包名和版本
        .\vcpkg.exe install mysql-connector-c:x64-windows-static
        # 或者
        .\vcpkg.exe install mysql:x64-windows-static
        
        # 查看实际安装的库文件
        Get-ChildItem installed\x64-windows-static\lib\*.lib | ForEach-Object { Write-Host $_.Name }
