name: Build Windows Libraries

on:
  workflow_dispatch: # 只允许手动触发

jobs:
  build-windows-libs:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: |
          vcpkg/installed
          vcpkg/buildtrees
          vcpkg/downloads
        key: vcpkg-${{ hashFiles('**/Cargo.toml') }}-${{ runner.os }}
        restore-keys: |
          vcpkg-${{ runner.os }}-
          vcpkg-
      
    - name: Install vcpkg
      run: |
        if (-not (Test-Path "vcpkg")) {
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
        } else {
          cd vcpkg
        }
        
    - name: Install zlib
      run: |
        .\vcpkg\vcpkg.exe install zlib:x64-windows-static
        
    - name: Install zstd
      run: |
        .\vcpkg\vcpkg install zstd:x64-windows-static
        
    - name: Install OpenSSL
      run: |
        .\vcpkg\vcpkg install openssl:x64-windows-static
        
    - name: Install MySQL
      run: |
        .\vcpkg\vcpkg install libmysql:x64-windows-static
        
    - name: Install PostgreSQL
      run: |
        .\vcpkg\vcpkg install libpq:x64-windows-static
        
    - name: Copy libraries and Windows SDK
      run: |
        mkdir libs
        # 复制 vcpkg 安装的静态库
        copy vcpkg\installed\x64-windows-static\lib\*.lib libs\
        
        # 重命名 OpenSSL 库以匹配 Rust 期望的命名
        copy libs\libcrypto.lib libs\crypto.lib
        copy libs\libssl.lib libs\ssl.lib
        
        # 重命名 MySQL 库以匹配 Rust 期望的命名
        copy libs\libmysql.lib libs\mysqlclient.lib
        
        # 复制 Windows SDK 库
        $sdkPath = "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\"
        if (Test-Path $sdkPath) {
            copy "$sdkPath\ws2_32.lib" libs\
            copy "$sdkPath\wsock32.lib" libs\
            copy "$sdkPath\dnsapi.lib" libs\
            copy "$sdkPath\netapi32.lib" libs\
        }
        
        # 创建 resolv.lib 的符号链接
        copy libs\ws2_32.lib libs\resolv.lib
        
    - name: List all libraries
      run: |
        dir libs\
        echo "=== Library files ==="
        Get-ChildItem libs\*.lib | ForEach-Object { Write-Host $_.Name }
        
    - name: Upload all libraries
      uses: actions/upload-artifact@v4
      with:
        name: windows-libs
        path: libs/
