name: Build Windows Libraries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

jobs:
  build-windows-libs:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        
    - name: Install zlib
      run: |
        .\vcpkg\vcpkg install zlib:x64-windows-static
        
    - name: Install zstd
      run: |
        .\vcpkg\vcpkg install zstd:x64-windows-static

    - name: OpenSSL
      run: |
        .\vcpkg\vcpkg install openssl:x64-windows-static

    - name: Copy Windows SDK libraries
      run: |
        mkdir libs
        copy vcpkg\installed\x64-windows-static\lib\*.lib libs\
        # 复制 Windows SDK 库
        copy "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\ws2_32.lib" libs\
        copy "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\wsock32.lib" libs\
        copy "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\dnsapi.lib" libs\
        # 创建 resolv.lib 的符号链接
        copy libs\ws2_32.lib libs\resolv.lib
        
    - name: List installed libraries
      run: |
        dir vcpkg\installed\x64-windows-static\lib\

    - name: List all libraries
      run: |
        dir libs\

    - name: Upload zlib library
      uses: actions/upload-artifact@v4
      with:
        name: zlib-windows-lib
        path: vcpkg/installed/x64-windows-static/lib/zlib.lib
        
    - name: Upload zstd library
      uses: actions/upload-artifact@v4
      with:
        name: zstd-windows-lib
        path: vcpkg/installed/x64-windows-static/lib/zstd.lib
        
    - name: Upload all libraries
      uses: actions/upload-artifact@v4
      with:
        name: windows-libs
        path: libs/
