name: Build Windows Libraries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

jobs:
  build-windows-libs:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        
    - name: Install zlib
      run: |
        .\vcpkg\vcpkg install zlib:x64-windows-static
        
    - name: Install zstd
      run: |
        .\vcpkg\vcpkg install zstd:x64-windows-static
        
    - name: List installed libraries
      run: |
        dir vcpkg\installed\x64-windows-static\lib\
        
    - name: Upload zlib library
      uses: actions/upload-artifact@v4
      with:
        name: zlib-windows-lib
        path: vcpkg/installed/x64-windows-static/lib/zlib.lib
        
    - name: Upload zstd library
      uses: actions/upload-artifact@v4
      with:
        name: zstd-windows-lib
        path: vcpkg/installed/x64-windows-static/lib/zstd.lib
        
    - name: Upload all libraries
      uses: actions/upload-artifact@v4
      with:
        name: windows-libs
        path: vcpkg/installed/x64-windows-static/lib/
